// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuFBt0O7jHCcF_9NsoslvNGKA0idjOqvM',
    appId: '1:1068183427813:web:9a05d7829d33799936120c',
    messagingSenderId: '1068183427813',
    projectId: 'flutterexample322',
    authDomain: 'flutterexample322.firebaseapp.com',
    storageBucket: 'flutterexample322.appspot.com',
    measurementId: 'G-2H56GL5RE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWfSfpW8WdnRrSkZh8_6C2unIkPwex7cg',
    appId: '1:1068183427813:android:0ff2554cd579296136120c',
    messagingSenderId: '1068183427813',
    projectId: 'flutterexample322',
    storageBucket: 'flutterexample322.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxm9tyvYLuLvXIlwe370nu5GMrZKl8VkI',
    appId: '1:1068183427813:ios:b8f274ca20b1002f36120c',
    messagingSenderId: '1068183427813',
    projectId: 'flutterexample322',
    storageBucket: 'flutterexample322.appspot.com',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxm9tyvYLuLvXIlwe370nu5GMrZKl8VkI',
    appId: '1:1068183427813:ios:b8f274ca20b1002f36120c',
    messagingSenderId: '1068183427813',
    projectId: 'flutterexample322',
    storageBucket: 'flutterexample322.appspot.com',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuFBt0O7jHCcF_9NsoslvNGKA0idjOqvM',
    appId: '1:1068183427813:web:f9956c18d8f75bbf36120c',
    messagingSenderId: '1068183427813',
    projectId: 'flutterexample322',
    authDomain: 'flutterexample322.firebaseapp.com',
    storageBucket: 'flutterexample322.appspot.com',
    measurementId: 'G-D3GE67JHCS',
  );
}
